# Generated by Django 6.0.1 on 2026-01-19 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_aboutsection_faq_gallery_herosection_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='achievements',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='position',
            field=models.CharField(choices=[('president', 'President'), ('vice_president', 'Vice President'), ('secretary', 'Secretary'), ('treasurer', 'Treasurer'), ('event_coordinator', 'Event Coordinator'), ('public_relations', 'Public Relations'), ('member', 'Member'), ('advisor', 'Advisor')], max_length=50),
        ),
    ]
