# Generated by Django 6.0.1 on 2026-01-19 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_gallery_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='show_in_slider',
            field=models.BooleanField(default=False, help_text='Show this event in the homepage slider'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='show_in_slider',
            field=models.BooleanField(default=False, help_text='Show this image in the homepage slider'),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='show_in_slider',
            field=models.BooleanField(default=False, help_text='Show this article in the homepage slider'),
        ),
    ]
